name: publish_tutorials

on:
  push:
    branches:
    - master
    paths:
    - 'content/tutorials/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: publish-to-git
      uses: ./.github/actions/gha-publish-to-git
      id: publish
      with:
        repository: grafana/website
        branch: tutorials-sync
        host: github.com
        github_pat: '${{ secrets.GH_BOT_ACCESS_TOKEN }}'
        source_folder: content/tutorials
        target_folder: content/tutorials
    - shell: bash
      run: |
        test -n "${{ steps.publish.outputs.commit_hash }}"
        test -n "${{ steps.publish.outputs.working_directory }}"